import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  // mods: [{type: 'autogenerated', dirName: 'mods'}],
  modpacks: [{type: 'autogenerated', dirName: 'modpacks'}],
  app: [{type: 'autogenerated', dirName: 'app'}],
  support: [{type: 'autogenerated', dirName: 'support'}],
  marketplace: [{type: 'autogenerated', dirName: 'marketplace'}],
};

export default sidebars;
