// @ts-check
/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  mods: [{type: 'autogenerated', dirName: 'mods'}],
  modpacks: [{type: 'autogenerated', dirName: 'modpacks'}],
  app: [{type: 'autogenerated', dirName: 'app'}],
  support: [{type: 'autogenerated', dirName: 'support'}],
  marketplace: [{type: 'autogenerated', dirName: 'marketplace'}],
};

module.exports = sidebars;
